#git@github.com:Nirav2311/course-material.git

language: node_js

node_js:
  - "10.9.0"

cache: npm

env:
  - NOW_TOKEN=AyaH3cv1D3rteERgEuRHDXpX

before_install:
  - "npm config set spin false"
  - npm i -g now

install:
  - npm install

script:
  - npm run build
  - npm run test

deploy:
  provider: script
  script: "scripts/deploy.sh"  
  skip_cleanup: true

