# https://github.com/NaguitSirAngel

language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
  - mkdir dist
  - cd dist
  - ls -la

install:
  - ls -la
  - npm install
  - ls -la
