#https://github.com/anita-russo/
language: node_js

node_js:
  - 10.9.0

cache: npm

install:
  - npm install

script:
  - npm run build
  - npm run test

before_install:
  - "npm config set spin false"
  - npm i -g now

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true

env:
  - NOW_TOKEN="yUvrOYHMsM09Jt8WLPQU7avl"

script: ./scripts/deploy.sh
